import "bootstrap/dist/css/bootstrap.css";
import Head from "next/head";
import Body from "../components/Body";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <Navbar styles={styles} />
        <Body styles={styles} />
      </main>

      <Footer styles={styles} />
    </div>
  );
}
